name: redstone
version: 0.6.7
authors:
  - Luiz Mineo <luiz.mineo@gmail.com>
  - Kenneth Endfinger <kaendfinger@gmail.com>
  - Austin Cummings <austincummings95@gmail.com>
  - Cristian Garcia <cgarcia.e88@gmail.com>
  - Joel Trottier-Hebert <iamquebecois@gmail.com>
description: A metadata driven microframework for Dart
homepage: http://redstonedart.org
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  collection: ">=1.2.0 < 1.13.0"
  di:
    git:
      url: git://github.com/hterkelsen/di.dart.git
      ref: roll-deps
  grinder: ">= 0.8.0+3 < 0.9.0"
  mime: ">= 0.9.3 < 0.10.0"
  http: ">=0.11.3+3 < 0.12.0"
  http_parser: '>=2.2.1 < 4.0.0'
  http_server: ">=0.9.5+1 < 0.10.0"
  route_hierarchical: ">= 0.7.0 < 0.8.0"
  shelf: ">= 0.6.4+3 < 0.7.0"
  stack_trace: ">= 1.6.5 < 1.7.0"
dev_dependencies:
  test: ">= 0.12.6+1 < 0.13.0"
